import os
import sys
import ast
import subprocess

TARGET_FILE = "test_day11_assignment.py"

def check_ast():
    if not os.path.exists(TARGET_FILE):
        print(f"[ERROR] {TARGET_FILE} not found.")
        return False

    with open(TARGET_FILE, "r") as f:
        tree = ast.parse(f.read())

    fixture_ok = False
    param_list = []

    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == "db_client":
            # Check decorator arguments
            for dec in node.decorator_list:
                if isinstance(dec, ast.Call) and isinstance(dec.func, ast.Attribute) and dec.func.attr == "fixture":
                    for kw in dec.keywords:
                        if kw.arg == "params" and isinstance(kw.value, ast.List):
                            fixture_ok = True
                            for elt in kw.value.elts:
                                if isinstance(elt, ast.Constant):
                                    param_list.append(elt.value)
                                elif isinstance(elt, ast.Name):
                                    param_list.append(elt.id)

    if not fixture_ok:
        print("   [FAIL] db_client is not decorated with @pytest.fixture using the 'params' keyword.")
        return False

    expected_params = {"sqlite", "postgres", "mysql"}
    if set(param_list) != expected_params:
        print(f"   [FAIL] db_client params argument should be ['sqlite', 'postgres', 'mysql']. Got: {param_list}")
        return False

    print("   [PASS] AST checks for Day 11 verify OK.")
    return True

def run_tests():
    # Run pytest and capture results
    cmd = [sys.executable, "-m", "pytest", TARGET_FILE, "-v"]
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.returncode, result.stdout

def main():
    print("====================================================")
    print("[RUNNING] Running Verification Suite for Day 11...")
    print("====================================================")

    if not check_ast():
        sys.exit(1)

    print("\nRunning pytest on your parameterized fixture tests...")
    code, out = run_tests()
    if code != 0:
        print("[FAIL] Test suite execution failed! Output:")
        print(out)
        sys.exit(1)
        
    # Check that 3 tests ran
    if "3 passed" not in out:
        print("[FAIL] Expected exactly 3 passed tests generated by parameterization, check output:")
        print(out)
        sys.exit(1)
        
    print("[PASS] Scoped and parameterized fixtures executed successfully (3 runs generated).")
    print(out)
    
    print("\n----------------------------------------------------")
    print("[SUCCESS] You have completed Day 11 Assignments successfully!")
    sys.exit(0)

if __name__ == "__main__":
    main()
